### ISSUE TITLE
Example has a bad example password

### ISSUE THREAD

**Issue by AshleyPinner** [bwesterb/pol#11]
The example in the readme.md has the following:

```
# alphanumeric password that would take ages to bruteforce with 10 tries per second
$ pol generate --sdtout --kind alphanum --web-crack-time ages
NNrZ9g8Sy
```

Looking at zxcvbn, it suggests the following for that example:

```
guess times:
100 / hour:	centuries	(throttled online attack)
10  / second:	4 months	(unthrottled online attack)
10k / second:	1 day	(offline attack, slow hash, many cores)
10B / second:	less than a second	(offline attack, fast hash, many cores)
```

It might be worth providing an example that lives up to the 10/sec suggested by the readme.

**Comment by bwesterb** [comment]
Thanks for being careful!

1. The example is a randomly chosen 8 letter alphanumeric password.  That's one out of `(26+26+10)**8`.  If one guesses 10 per second, then we can compute the number of years to try them all:

 ```
 >>> (26+26+10)**8 / 10. / 60 / 60 / 24 /365
 692351.932981025
 ```
 
 I think it's appropriate to call that ages.
2. `zxcvbn` is (on purpose) conservative: it sometimes sees patterns where there aren't.
3. Off course, strictly speaking every published password is a bad password.

**Comment by AshleyPinner** [comment]
For 2: zxcvbn isn't suggesting that there's any pattern to `NNrZ9g8Sy` though, it's suggesting it's a brute force attack. It's also suggesting it should be able to get that in 1000000001 guesses.

For 1: I mean, I agree with your maths, but that's the worst-case. An attacker doesn't need worst-case, as your password is less likely to be the last thing in the search space (which by nature of choice might appear in the first few search spaces just to eliminate people playing the odds, such as when PIN guessing starts with 0000 and then 9999)

NNrZ9g8Sy comes out to about 53.588 bits of entropy, and IMO "ages" should be at least 72 bits of entropy. 

As a compromise, throw `u1` on the end; even zxcvbn suggest that'll take 31 years, which is enough to consider "ages" in most definitions. Though one is totally mindful of your third point, your example should at least agree with popular methods of evaluating password strength ;)

**Comment by MacGyverNL** [comment]
I looked into zxcvbn's code, because these numbers don't add up, and came across <https://github.com/dropbox/zxcvbn/commit/d20704b7328b10ec6eef0e4b204893c1a8e6ed0a>. To quote, 

'''
  after experimenting with more complicated models to try to estimate
  guessability from markov attacks, bruteforce cardinality is now a
  constant 10 across the board. even 26 for all-lowercase bruteforce regions
  is almost certainly overestimating bruteforce guessability, given password
  character sequences are highly predictable in practice and crackers have
  excellent statistical modes. finding ways to make bruteforce
  estimation more realistic would be a fun future research project.
'''

Although I understand the need for zxcvbn to be conservative, I would argue that this is an unfair estimate for passwords which have been found to be "bruteforcable at best" *and* "randomly generated".
